sudo: false
language: node_js
node_js:
  - 10
cache: yarn
before_deploy:
  - rm .gitignore
  - yarn build
  
deploy:
  skip_cleanup: true
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: WxgE4r8cOC7KxcLLmJQHcMp4jmaktX5XEnUH6gB+MUPG21EygfG6xP2Ldbq/fPYPCGRohZEWvM3iHO3W8x2tZSLUcb/A8iDAcugtSYB3cbUGc0snU5Rwf8wvtsDUhxO3KALLFzubgKLbfx5B2TQo/CjmGRLWy7WHsoaPc+9IQxRxMQfhCnhzbv7mpSL2rms6bVNsZ0nYeICBcge4d49gT/Pw7D9oRddzkMxPpfFuGZeHbqZJYjO0v1pF6MFpgw7oXqyVfR4MmUiRlY4r6JlFN7pNLg3Rpq3EpIj6+2AxTb9HeJ78bfCYx4uAqFNzSS1GJlEM/cDNHO/1ep4kRx7UprxK3SMPK9CAycG1AeTfgH45BziYsev8NfZJXTHrpxmWw5wVjcQFdUmDWY9o6zFw6/xaMU+TWde3VErCozTe6/driDfULiI5cdI0dW3xSDaMfQ1emF+rKiGhnU+nq4lG/2310eA063xif20Jcr09nCEFTsNO1TekmwVy54fkvW7BUTo8w+T7eVur24MD80vSov1uiUCcg7MzSl4EtQMrphWmft+ttVQqEPzCx4wqOFzULdvkRE4x7s9xPZpKj761J3m9d9ZQ2Fwe+DKdMzic6zpou7eryoLf36yaN4da/jWDlcTmcJvXX9wh4K+i26dPAXEIGst7olU/hrLb9L6zrxk=
  on:
    tags: true